[project]
name = "task-manager-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.5",
    "psycopg[binary]>=3.2.3",
    "pydantic>=2.9.2",
    "uvicorn[standard]>=0.32.0",
]
